#!/bin/bash
cd pep.py
screen -S pep.py -X quit
cd ..
cd lets
screen -S lets -X quit
cd ..
cd hanayo
screen -S hanayo -X quit
cd ..
cd rippleapi
screen -S rippleapi -X quit
cd ..
cd avatar
screen -S avatar -X quit
cd ..
